config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'posts#index'
  resources :posts, only: [:index, :new, :create, :show, :update]
  get 'categories/:category_id', to: 'posts#index', as: 'category'
  get 'users/:user_id', to: 'posts#index', as: 'user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :category

  belongs_to :user

  has_many :comments

  def self.filter(args)
    if args[:category_id]
      Post.where(['category_id = ?', args[:category_id]])
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def is_admin?
    #return role.name == 'admin'
    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post
  
  def new
    @comment = Comment.new
  end

  def find_post
    @post = Post.find(params[:post_params])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.filter(params)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Success!"
      redirect_to posts_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
      params.require(:post).permit(
      :title,
      :content,
      :category_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class Account::UsersController < Account::AccountController
  def index
    @user = current_user
  end

  def update
    @user = Users.find(current_user.id)

    if @user.update_attributes(user_params)
      redirect_to account_user_index_path
    else
      render template: 'account/user/index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Start Bootstrap Template
    = stylesheet_link_tag       "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag    "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    / Navigation
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-targer" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Blog", root_url, class: "navbar-brand"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if user_session != nil
              %li
                = link_to "New Post", new_post_path
            - if current_user
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?"
            - else
              %li
                = link_to "Login", new_user_session_path
            - Category.all.each do |category|
              %li= link_to category.name, category_path(category.id)
    / Page Content
    .container
      .row
        .col-lg-12.text-center
          - flash.each do |a, b|
            .alert.alert-success
              = b
          = yield
    :css
      body{padding-top:70px;}

app/views/posts/index.html.haml
%h2 5 derniers articles
%ul
  - @post.last(5).each do |post|
    %li= link_to post.title, posts_path(@post)
    = post.content

app/views/posts/new.html.haml
%h2 New Post
%hr/
= form_for @post, html: { multipart: true } do |f|
  .form-group
    = f.label :title, class: 'form-label required'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :category_id, class: 'form-label required'
    = f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}
  .form-group
    = f.label :content, class: 'form-label required'
    = f.text_area :content, class: 'form-control'
  %br/
  = f.submit

app/views/posts/show.html.haml
%ul
  %li= @post.title
  %li= @post.content
  = form_for @comment, html: { multipart: true } do |c|
    .form-group
      = c.label :email, class: 'form-label required'
      = c.text_field :email, class: 'form-control'
    .form-group
      = c.label :pseudo, class: 'form-label required'
      = c.text_field :pseudo, class: 'form-control'
    .form-group
      = c.label :content, class: 'form-label required'
      = c.text_area :content, class: 'form-control'
    %br/
    = f.submit